name: On Pull Request

on:
  pull_request:
    branches:
      - "*" # Every branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set version changed
        id: set-version-changed
        run: |
          current_version=$(git show HEAD:package.json | grep '"version"' | cut -d'"' -f4)
          last_version=$(git describe --tags --abbrev=0 | sed 's/v//')

          echo $current_version
          echo $last_version

          if [ "$current_version" != "$last_version" ]; then
            echo "Version number has changed in the pull request."
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "Version number has not changed in the pull request."
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
          fi

          echo $GITHUB_ENV

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: |
      github.ref == 'refs/heads/master' &&
      github.event_name == 'push'

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
