name: On Push

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        uses: justincy/github-action-npm-release@v1.2.0
        id: release

      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set version changed
        id: set-version-changed
        run: |
          current_version=$(git show HEAD:package.json | grep '"version"' | cut -d'"' -f4)
          last_version=$(git describe --tags --abbrev=0 | sed 's/v//')

          if [ "$current_version" != "$last_version" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
            echo "Version changed!"
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
            echo "Version NOT changed"
          fi

          echo "Version changed: "
          echo ${{ env.VERSION_CHANGED }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
