name: On Pull Request

on:
  pull_request:
    branches:
      - '*' # Every branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier:check

      - name: Run unit tests
        run: npm test

      - name: Run lint
        run: npm run lint
