name: On Pull Request

on:
  pull_request:
    branches:
      - "*" # Every branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.ref == 'refs/heads/master' &&
      github.event_name == 'push' &&
      steps.version.outputs.changed == 'true'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
